### ISSUE TITLE
[Feature] Convert the repository to a template repository 

### ISSUE THREAD

**Issue by yu-iskw** [jeffmendoza/dot-allstar-quickstart#1]
## Motivation
GitHub's fork doesn't allow us to use a different name from that of a source repository. Meanwhile, a template repository enables us to easily name a repository to "fork". So, if the repository is a template repository, it would be easier to reuse it.

**Comment by jeffmendoza** [comment]
Great idea! sorry I have not done this sooner. Let me take a look

**Comment by jeffmendoza** [comment]
Ok, I think it should be ready, thanks again.

**Comment by yu-iskw** [comment]
@jeffmendoza Thank you for quickly handling it!
